### ISSUE TITLE
import.php sql INSERT bug

### ISSUE THREAD

**Issue by pepicek** [FarnetInternet/fio_import#1]
Řádek 72 v import.php
$sql = "INSERT INTO platbyTest (transactionId, datum, objem, mena, protiucet, kodBanky, nazevBanky, typ, provedl, idPokynu, varSymbol) ...

správně má být podle definované sql tabulky "variabilnySymbol" namísto "varSymbol"

$sql = "INSERT INTO platbyTest (transactionId, datum, objem, mena, protiucet, kodBanky, nazevBanky, typ, provedl, idPokynu, variabilnySymbol) ...

a nebo změnit definici sql tabulky na radku 42 z
  `variabilnySymbol` varchar(10) DEFAULT NULL,
na
  `varSymbol` varchar(10) DEFAULT NULL,

**Comment by FarnetInternet** [comment]
Dnes proběhla komplexní aktualizace kódu a byli provedeny úpravy 😊
